### ISSUE TITLE
windows10下小红伞报毒

### ISSUE THREAD

**Issue by Bryan2333** [osfans/PIME#18]
![default](https://user-images.githubusercontent.com/31512600/30249094-c237e6d4-9666-11e7-8792-e65ecdc2db8a.JPG)

**Comment by osfans** [comment]
建議先試試PIME
https://github.com/EasyIME/PIME/releases

**Comment by InSb** [comment]
另，若追求稳定，可以试用[版本1.0.0](https://github.com/EasyIME/PIME/releases/tag/v1.0.0)。
