### ISSUE TITLE
是不是因为主程序没有签名？

### ISSUE THREAD

**Issue by HashimaL** [osfans/PIME#20]
腾讯管家各种报毒。system.dll和PIMElauncher.exe都循环报毒。
另外程序的名字是不是可以统一一下，安装文件写的是PRIME，主程序是PIME，有些地方体现的是RIME。个人认为可以统一一下在强调RIME的前提下以PRime为主。

**Comment by osfans** [comment]
應該是沒有簽名。PIME好像有簽名。以後合併過去，還是以pime爲主。
