### ISSUE TITLE
词库记忆功能如何开启

### ISSUE THREAD

**Issue by product-think2049** [osfans/PIME#26]
一些人名、习惯性用语我多次输入后仍然没有记忆，不知道哪里可以开启？一直没有看到配置的选项，谢谢！

**Comment by osfans** [comment]
有的，可以參考去rime之家修煉下：
https://github.com/rime/home/wiki

**Comment by product-think2049** [comment]
谢谢

**Comment by product-think2049** [comment]
![image](https://user-images.githubusercontent.com/13373715/32883300-f40c2318-caf1-11e7-9487-14962e118397.png)
@osfans  我找到了原因，好像是我的词典文件一直记录在10月那一天，开机状态下输入名字后是会词库记忆的，关机、或者重启之后，就消失了，rime之家文件还有一篇没有看完

**Comment by product-think2049** [comment]
https://github.com/rime/home/wiki/RimeWithSchemata
这个链接感觉是最有用的

**Comment by osfans** [comment]
原來是消失啦

**Comment by product-think2049** [comment]
![image](https://user-images.githubusercontent.com/13373715/32928291-2e9d528c-cb8c-11e7-8aca-28eaf3496dbf.png)
链接文章看完还是没有找到词库文件没有写入的原因，昨天到现在那个词库文件一直记忆的是10月16号内容，没有变动过
@osfans

**Comment by Equim-chan** [comment]
遇到了类似的问题。而且还有个特征，当自造词无法使用时，词频调整也会失效。

也可能是上游的问题，参考 https://github.com/rime/home/issues/128
