### ISSUE TITLE
当前 branch build 后显示乱码

### ISSUE THREAD

**Issue by nameoverflow** [osfans/PIME#27]
![image](https://user-images.githubusercontent.com/10287709/33241504-4dc5fef8-d301-11e7-8783-e769ae40caa7.png)

是因为默认的字符集和系统不同？

**Comment by osfans** [comment]
手動編輯過rime_ime.py文件了？

**Comment by nameoverflow** [comment]
没有，cmake 之后直接用 vs 2017 打开后 build。而且 rime_ime.py 似乎也没有包含有这些文本？

输入法的输入框内也是显示的乱码。

**Comment by nameoverflow** [comment]
使用 build.bat 结果似乎是正常的，但是用 VS 2017 打开 sln 选择 Release 进行构建后使用产生乱码

**Comment by osfans** [comment]
總之應該都是utf-8編碼，而不應該用gbk或者big5
