### ISSUE TITLE
不适应新的 librime

### ISSUE THREAD

**Issue by mrhso** [osfans/PIME#30]
新的 librime 的补丁机制已经发生了改变，不适应可能不影响使用，但会在部分方面产生严重的后果。

**Comment by mrhso** [comment]
小狼毫同样存在这个问题，只是小狼毫的症状更为严重，直接无法使用：
https://github.com/rime/weasel/issues/99

**Comment by lotem** [comment]
I'm working on https://github.com/rime/librime/issues/164

**Comment by Prcuvu** [comment]
我需要可能产生严重后果的部分的细节，以便测试 rime/librime#173 在 PRIME 中的效果。

**Comment by mrhso** [comment]
补丁无法应用，现在我又没法重现这个问题了。
可能是当时我操作不当吧。

**Comment by mrhso** [comment]
Fixed.
