### ISSUE TITLE
现在还有人在用吗，感觉17年之后评论和软件没有什么更新了

### ISSUE THREAD

**Issue by Franklyn1987** [osfans/PIME#33]
现在还有人在用吗，感觉17年之后评论和软件没有什么更新了

**Comment by osfans** [comment]
可以去QQ羣討論看看。librime有更新，爭取正月跟上。

**Comment by Equim-chan** [comment]
在用的，另外原版前端小狼毫最近也活跃起来了，他们正在研究怎么 port 到 win10 上。

**Comment by osfans** [comment]
小狼毫已經可以在win10上用了

**Comment by osfans** [comment]
本人沒有用win10，所以更新比較慢。
